# In the settings.yml file we can add constants that we don't want the public to see
#
# We load these files in application.rb via:
#  SETTINGS = YAML.load(File.read(File.expand_path('../settings.yml', __FILE__)))
#  SETTINGS.merge! SETTINGS.fetch(Rails.env, {})
#  SETTINGS.symbolize_keys!
#
# To access these constants (anywhere in the app), just do SETTINGS[:constant]
# where 'constant' is the name of the constant in here
#
# IMPORTANT
# It's super important that you gitignore settings.yml and NEVER commit it to the repo.
# If you do you will need to change all the secrets stored here,
# as even if later removed it'll still be viewable in the git history
#

default:
  stugov_api_user: bridgeapi_middleware_user
  stugov_api_pass: bridgeapi_middleware_pass
  stugov_api_base_url: base_url_for_stugov_api_middleware
  api_key_salt: put_a_random_salt_for_hashing_api_keys_here

development:
  <<: *default
  db: db/development.sqlite3
  # currently using sqlite3 for dev db, no auth needed

production:
  <<: *default
  db: bridge_api_production # We don't want the public knowing how we name our dbs
  db_user: username
  db_pass: password

staging:
  <<: *default
  db: bridge_api_staging
  db_user: username
  db_pass: password

